name: Build & Release .NET 9 Console App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. 0.0.1)'
        required: true
        default: '0.0.0-test'
          
jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            rid: win-x64
            artifact_name: windows-build
            zip_name: build-win.zip
            exe_name: ChatRoom.exe
          - os: ubuntu-latest
            rid: linux-x64
            artifact_name: linux-build
            zip_name: build-linux.zip
            exe_name: ChatRoom

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          include-prerelease: true

      - name: Restore
        run: dotnet restore

      - name: Publish
        shell: bash
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF_NAME#v}"
          fi
      
          echo "Building version $VERSION for runtime ${{ matrix.rid }}"
      
          dotnet publish -c Release -r ${{ matrix.rid }} \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:IncludeNativeLibrariesForSelfExtract=true \
            -p:PublishTrimmed=false \
            -p:Version=$VERSION \
            -o publish

      - name: Zip build (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: zip -r ${{ matrix.zip_name }} publish
        shell: bash

      - name: Zip build (Windows)
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path publish\* -DestinationPath ${{ matrix.zip_name }}
        shell: powershell

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.zip_name }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: ./windows

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-build
          path: ./linux

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            windows/build-win.zip
            linux/build-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
